### ISSUE TITLE
rm: cannot remove 'user.js': No such file or directory

### ISSUE THREAD

**Issue by Xenchrarr** [bitleaf/optimize-ubuntu#24]
https://github.com/bitleaf/optimize-ubuntu/blob/bf5f24223a52e362f261ef535d9b7624bff4b26b/optimize-ubuntu-18-04.sh#L246

**Comment by MathiasRenner** [comment]
@Xenchrarr An obvious bug - thank you very much for reporting it! I'll provide a fix soon.

**Comment by MathiasRenner** [comment]
Fixed by https://github.com/bitleaf/optimize-ubuntu/commit/cda17283eb92404ef29763b23ea7a618206a0c83

**Comment by MathiasRenner** [comment]
@Xenchrarr Can you confirm please?

**Comment by Xenchrarr** [comment]
Yes, the bug is gone.sudo bash /tmp/optim.sh

**Comment by MathiasRenner** [comment]
@Xenchrarr Thanks!
