### ISSUE TITLE
Works 99% on Kubuntu (KDE)

### ISSUE THREAD

**Issue by gabriellluz** [bitleaf/optimize-ubuntu#26]
Hi there!

I love your script. It works great. The only downside is that it doesn't work for KDE.
Maybe adding support for KDE would be great. Tell me if you need anything. See you.

**Comment by MathiasRenner** [comment]
@gabriellluz Thanks for your nice feedback :-)
 
What exactly is the Problem with KDE? Maybe the packages are named differently? Do you have screnshots or error messages?

I have limited time, so it would be great if you could provide a PR to fix it ;-)

**Comment by gabriellluz** [comment]
Hi there. Unfortunately I can't provide a PR since I don't know how to code anything. Sorry.

**Comment by gabriellluz** [comment]
I'll copy the log.

**Comment by MathiasRenner** [comment]
No response...
